--[[
	Opisy pojazdów
]]--
veh_desc = {}

veh_desc[400] = "Już w latach 80 amerykańska myśl techniczna poszła o krok dalej i stworzyła wóz który będzie nadawał się idealnie fanów jazdy offroad jak i pojemnej rodzinki z przedmieść. Landstalker to Jeep o stosunkowo małych wymiarach oraz małych osiągach, jego silnik ledwo co napędza sam pojazd. Jeśli szukasz przeciętnego auta dla przeciętnego człowieka to myślę że dobrze trafiłeś."
veh_desc[401] = "Konstruktorzy projektując ten wóz chcieli stworzyć sportową maszyne na chudą kieszeń, lecz jednocześnie tym samym sami polecieli po kosztach i takim oto sposobem została stworzona Bravura - brzydkie kaczątko wśród tanich wozów sportowych. Skoro mówimy o wozach sportowych, to nie oczekujcie zawrotnej prędkości, bo przydomek sportowy został tylko na kartce papieru w fazie projektowania."
veh_desc[402] = "Agersywny, ostry, głośny, drogi, duży - typowy amerykański wóz sportowy. Buffalo stał się ikoną amerykańskich pościgów z lat 90. Wóz został zaprojektowany na platformie F-Body z rodziny prawdziwych amerykańskich wozów sportowych. Pod jego maską znajduje się turbodoładowana jednostka V6 zdolna rozpędzić pojazd do prędkości przy której kierowca wylatuje za szybę. Jeśli więc masz pieniądze, chęć i jaja to ten wóz jest dla ciebie. "
veh_desc[403] = "Tego pojazdu nie trzeba opisywać, typowy ciągnik siodłowy który został wyprodukowany w fabrykach Texas'u."
veh_desc[404] = "[[ Tutaj jakiś autystyczny opis był ]]"
veh_desc[405] = "Widok tej czarnej limuzyny w nocy pod oknem potrafi wywołać ciarki na plecach, sentinel stał się ulubionym wozem europejskich mafiozów jak i też przesiąkniętych korupcją polityków. Jeśli masz pieniądze i zadatki na taką personę to możesz śmiało kupić tą europejską limuzyne."
veh_desc[406] = "Dumper to gigantycznych rozmiarów wywrotka wykorzystywana w kamieniołomach."
veh_desc[407] = "Amerykański wóz strażacki z gigantycznymi amerykańskimi zderzakami."
veh_desc[408] = "Nie chcesz jeździć tym wozem, zaufaj mi."
veh_desc[409] = "Ulubiony wóz pimpów w różowych garniturach oraz bananowych dzieciaków z bogatych rodzin... ale każdy ma jakieś marzenia."
veh_desc[410] = "Ten amerykański kompaktowy szkrab zasilany jednostką R4 do dziś jest zagadką dla samych producentów... dlaczego został wyprodukowany?"
veh_desc[411] = "Infernus to demon prędkości zaprojektowany i wyprodukowany przez amerykański oddział japońskiego koncernu motoryzacyjnego. Jego prosty kształt i dość pozornie niegroźna sylwetka jest tylko pozorem grzecznego sportowego samochodu dla średniej klasy społecznej. Infernus jest zasilany potężną jednostką V12 dzięki której wóz jest w stanie prześcignąć więszkość supersamochodów jakie wyszły na rynek. Jeśli nie jesteś miliarderem albo nie okradłeś banku to nawet nie myśl o tym samochodzie."
veh_desc[412] = "Kupując egzemplarz voodoo prawdopodobnie w środku zastaniesz zapach kubańskich cygar i rozsypaną kokaine, to właśnie ten wóz stał się ulubionym wozem kubańczyków i haitańczyków z florydy w latach 80. Jego niepozorny wygląd kryje pod maską potężny silnik, a konstrukcja zawieszenia zapewnia niesamowitą przyczepność. Dziś jest już tylko starym gratem, lecz jego dusza ciągle żyje."
veh_desc[413] = "Ulubiony VAN federalnych, ta furgonetka może się popisać niesamowitą pojemnością ładowniczą, między innymi sprzętu do podsłuchiwania... i w sumie tyle."
veh_desc[414] = "Osioł... brzydki, głupi i wolny - takimi słowami można opisać tą furgonetkę, a nazwa nie jest przypadkowa."
veh_desc[415] = "Wiele osób uwielbia go za kształt, inni za moc, a jeszcze inni za cene. Cheetah jest jednym z niewielu sportowych wozów który nie odstrasza ceną a oferuje ciekawego... siebie. Dobry wóz dla dobrze zarabiających."
veh_desc[416] = "Ambulans amerykańskiego koncernu motoryzacyjnego, kawał amerykańskiej kultury."
veh_desc[417] = "Śmigłowiec transportowy zdolny lądować na wodzie."
veh_desc[418] = "Jeśli masz wielką rodzinę i masz gdzieś opinie innych... kupuj go śmiało. Niczym cie nie zachwyci, no może jedynie tym że nikt ci go nie ukradnie."
veh_desc[419] = "Kiedyś amerykański pancernik, teraz rdzewiejący grat - choć jego blask był mocny to dziś już całkowicie wygasł. Za kilka dolarów mogę ci go sprzedać dorzucając do tego choinkę zapachową w kolorach szachownicy."
veh_desc[420] = "Masowo produkowany premier z wzmocnionymi zderzakami."

-- znowu czesc
veh_desc[481] = "Wyczynowy rower stworzony głównie dla młodszych osób, które lubią aktywnie spędzać czas."

-- czesc
veh_desc[574] = "Mała budka żelaza z szczotkami pod podwoziem. Denerwująca zwłaszcza gdy masz zielone światło a wyjeżdża Ci zamiatarka przed maske."
veh_desc[575] = "Stary samochód który nie zaskakuje niczym poza wyglądem. Jest duży, ociężały i brakuje mu mocy. Najlepsza zabawka alfonsów."
veh_desc[576] = "Jeden z amerykańskich klasyków. Do dziś jest rozpoznawany oraz chwalony przez użytkowników. Mniejsza część z nich zamienia go na kolorowe Low-Low."
veh_desc[577] = "Samolot pasażerski który oferuje jedynie loty pierwszą klasą. Dzięki wygodzie oraz swobodzie podczas lotu pasażerowie są zadowoleni."
veh_desc[578] = "Laweta dzięki której nie musisz się martwić o transport swojego wraku z autostrady gdy zabraknie Ci paliwa."
veh_desc[579] = "Niby pojazd terenowy lecz używany jest na drogach asfaltowych. Najczęściej widywany wśród przestępczej społeczności."
veh_desc[580] = "Samochód chociaż ciężko tak na prawdę go nazwać ze względu na luksus jaki nam oferuje. Został stworzony dla osób  wyższych sfer którzy wymagają wiele od swojego samochodu."
veh_desc[581] = "Motocykl który mimo agresywnego wyglądu nie zaskakuje swoją mocą oraz osiągami. Używany przez amatorów jazdy na dwóch kolach."
veh_desc[582] = "Van przystosowany dla dziennikarzy. W środku znajdziemy jeden z najlepszych sprzętów stacjonarnych oraz najszybsze łącza bezprzewodowe."
veh_desc[583] = "Mały pojazd lotniskowy służący do podstawiania schodów do samolotów oraz przewozu bagażu na przyczepkach."
veh_desc[584] = "Cysterna służąca do przewozu paliwa na całym stanie San Andreas."
veh_desc[585] = "Średniej klasy sedan który jest dość popularny. Dzięki swoim gabarytom zapełnił sobie miejsce w ścisłej czołówce niepraktycznych pojazdów."
veh_desc[586] = "Motocykl dla pasjonatów. Używany jest do długich podróży po stanie. Dzięki swojej wielkości zaskakuje wygodą oraz komfortem jazdy."
veh_desc[587] = "Sportowe auto z europy, niby zaskakuje wyglądem lecz osiągami nie zachwyca."
veh_desc[588] = "Van dość specyficzny, wyróżnia się w tłumie swoją wielką parówką na dachu. Kontrowersyjne jest to że jeżdżą nim afro amerykanie."
veh_desc[589] = "Mały hatchback z europy używany przez rodziny z niższych sfer ze względu na cenę oraz dostępność części."
veh_desc[590] = "Wagon pociągu w którym przewożone są przeróżne rzeczy. Głównie jest używany przez imigrantów by przekroczyć granice."
veh_desc[591] = "Chłodnia w której jedne z najsilniejszych maszyn lądowych przewożą świeże mięso do naszych sklepów."
veh_desc[592] = "Samolot pasażerski latający po stanie San Andreas. Oby tylko nie spadł."
veh_desc[593] = "Mały samolot używany przez amatorów lotnictwa którzy zaczynają swoja przygodę."
veh_desc[594] = "Doniczka."
veh_desc[595] = "Łódź używana do przemieszczania się z punktu A do punktu B. Wyróżnia się działem maszynowym na końcu."
veh_desc[596] = "Radiowóz używany na terenie Los Santos i okolic. Jedyna różnica między tym a radiowozem z San Fierro jest oznaczenie na drzwiach."
veh_desc[597] = "Radiowóz używany przez departament policji. Dzięki zmodyfikowanemu silnikowi oraz mocnej bazie nadwozia może pozwolić sobie na brawurowe pościgi."
veh_desc[598] = "Starego typu radiowóz używany na terenach miasta Las Venturas. Tylko dlaczego tak bogate miasto ma tak stare radiowozy?"
veh_desc[599] = "Terenowy pojazd używany przez departament policji do jazdy po zboczach oraz miejscach w których nie dotrze zwykła jednostka."
veh_desc[600] = "Amerykański pickup który swoją sławę zdobył przez jednostkę V8 HEMi pracująca pod maską."
veh_desc[601] = "Opancerzony pojazd, tryskający wodą używany przez jednostki S.W.A.T w sytuacjach wyjątkowych."
veh_desc[602] = "Pojazd zza oceanu produkowany na masową skale jako super samochód. Ale czy na prawdę nim jest?"
veh_desc[603] = "Sportowy pojazd z mocną jednostką V8 pod maską. Dzięki swojej sylwetce wspaniale trzyma się drogi."
veh_desc[604] = "Krążownik szos, niegdyś pożądanie wielu rodzin. Dziś rdzewieje na złomowiskach."
veh_desc[605] = "Mały, ociężały pickup używany przez farmerów. Ale dlaczego go nie naprawili?"
veh_desc[606] = "Przyczepka używana do przewozu mniejszego bagażu na terenie lotniska."
veh_desc[607] = "Przyczepka używana do przewozu większych bagaży na terenie lotniska."
veh_desc[608] = "Schody przeznaczone do wejścia na pokład samolotu."
veh_desc[609] = "Starego typu samochód dostawczy, duży oraz pakowny. Często używany ze względu na tanią eksploatacje."
veh_desc[610] = "Maszyna rolnicza używana do przesiewania gleby."
veh_desc[611] = "Mała przyczepka służąca do przewozu niewielkiego bagażu."